import { existsSync, promises as fs } from "node:fs";
import {
  addComponentsDir,
  addImportsDir,
  addTemplate,
  createResolver,
  defineNuxtModule,
  useLogger,
} from "@nuxt/kit";
import { parse, relative, resolve } from "pathe";

export interface ModuleOptions {
  dir: string;
  componentPrefix: string;
}

const TEMPLATE_NAME = "nuxt-imperative-modals.d.ts";

const generateDtsTemplate = (data: {
  importLines: string;
  modalNames: string;
  propTypes: string;
}) => `/**
 * This file is generated by nuxt-imperative-modals. Do not edit manually.
 */

import type { ComponentEmit, ComponentProps, ComponentSlots } from "vue-component-type-helpers";

${data.importLines}

declare global {
  type ModalName = ${data.modalNames};

  interface ModalsPropsTypeMap {
${data.propTypes}
  }

  interface ModalsEmitTypeMap {
${data.propTypes.replace(/ComponentProps/g, "ComponentEmit")}
  }

  interface ModalsSlotsTypeMap {
${data.propTypes.replace(/ComponentProps/g, "ComponentSlots")}
  }
}

export {};
`;

const toPascalCase = (value: string) =>
  value
    .replace(/(^|[-_\s]+)(\w)/g, (_, __, char: string) => char.toUpperCase())
    .replace(/[^A-Za-z0-9]/g, "");

const normalizeDir = (value: string) => value.replace(/\\/g, "/").replace(/^\.\//, "");

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: "nuxt-imperative-modals",
    configKey: "imperativeModals",
    compatibility: {
      nuxt: "^3.17.0 || ^4.0.0",
    },
  },
  defaults: {
    dir: "app/modals",
    componentPrefix: "Modals",
  },
  async setup(options, nuxt) {
    const logger = useLogger("nuxt-imperative-modals");
    const resolver = createResolver(import.meta.url);
    const normalizedDir = normalizeDir(options.dir);
    const srcDirNormalized = normalizeDir(nuxt.options.srcDir);
    const dirRelativeToSrc =
      srcDirNormalized.endsWith("/app") && normalizedDir.startsWith("app/")
        ? normalizedDir.slice(4)
        : normalizedDir;

    const candidateDirs = [
      resolve(nuxt.options.srcDir, dirRelativeToSrc),
      resolve(nuxt.options.rootDir, normalizedDir),
    ];
    const modalDir = candidateDirs.find((dir) => existsSync(dir)) ?? candidateDirs[0];
    const importBase = dirRelativeToSrc;

    addImportsDir(resolver.resolve("./runtime/composables"));
    addComponentsDir({
      path: resolver.resolve("./runtime/components"),
      pathPrefix: false,
      global: true,
    });
    addComponentsDir({
      path: modalDir,
      prefix: options.componentPrefix,
      pathPrefix: true,
      global: true,
      watch: true,
    });

    const scanModals = async (dir: string): Promise<string[]> => {
      if (!existsSync(dir)) {
        return [];
      }

      const entries = await fs.readdir(dir, { withFileTypes: true });
      const files = await Promise.all(
        entries.map((entry) => {
          const fullPath = resolve(dir, entry.name);
          return entry.isDirectory() ? scanModals(fullPath) : fullPath;
        }),
      );

      return files.flat().filter((file): file is string => file.endsWith(".vue"));
    };

    const formatModalName = (filePath: string) => {
      const relPath = relative(modalDir, filePath);
      const { dir, name } = parse(relPath);
      const cleanName = name.replace(/modal$/i, "");
      const segments = [...dir.split(/[\\/]/), cleanName].filter(Boolean).map(toPascalCase);
      return `${segments.join("")}Modal`;
    };

    const renderContent = async () => {
      const files = await scanModals(modalDir);
      const entries = files.map((file) => {
        const relPath = relative(modalDir, file).replace(/\\/g, "/");
        return {
          name: formatModalName(file),
          importPath: `~/${importBase}/${relPath}`.replace(/\/+/g, "/"),
        };
      });

      if (entries.length === 0) {
        return `declare global {
  type ModalName = string;

  interface ModalsPropsTypeMap extends Record<string, Record<string, unknown>> {}
  interface ModalsEmitTypeMap extends Record<string, (...args: any[]) => void> {}
  interface ModalsSlotsTypeMap extends Record<string, Record<string, unknown>> {}
}

export {};`;
      }

      return generateDtsTemplate({
        importLines: entries
          .map((entry) => `import ${entry.name} from "${entry.importPath}";`)
          .join("\n"),
        modalNames: entries.map((entry) => `'${entry.name}'`).join(" | "),
        propTypes: entries
          .map((entry) => `    ${entry.name}: ComponentProps<typeof ${entry.name}>;`)
          .join("\n"),
      });
    };

    addTemplate({
      filename: TEMPLATE_NAME,
      write: true,
      getContents: renderContent,
    });

    nuxt.hook("prepare:types", ({ references }) => {
      references.push({ path: resolve(nuxt.options.buildDir, TEMPLATE_NAME) });
    });

    nuxt.hook("builder:watch", async (_, path) => {
      const changedPath = resolve(nuxt.options.rootDir, path);
      if (changedPath.startsWith(modalDir)) {
        logger.info(`Regenerating modal types for ${path}`);
        await nuxt.callHook("builder:generateApp");
      }
    });

    const modalFiles = await scanModals(modalDir);
    if (modalFiles.length > 0) {
      logger.success(`Loaded ${modalFiles.length} modals from ${normalizedDir}`);
    } else {
      logger.info(`No modals found in ${normalizedDir} yet.`);
    }
  },
});
